Repository E3SM-Project/e3sm_diags, pull requests merged in 2021-04, with the labels that each got.

#433 Rename CI/CD build and update docs
  .github/workflows/build_workflow.yml
  README.md
  docs/source/contributing.rst
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/releasing-e3sm-diags.rst
  docs/source/install.rst
Labels: DevOps, documentation

#437 Add ability for CI to skip required jobs to save build time and resources
  .github/workflows/build_workflow.yml
Labels: DevOps, enhancement

#438 Fix conditional for build step
  .github/workflows/build_workflow.yml
Labels: DevOps

#441 Disable MacOS in matrix testing to reduce build time and increase CI stability
  .github/workflows/build_workflow.yml
Labels: DevOps

#435 Add CDP Output Viewer guide in docs
  docs/source/dev_guide/_static/cdp_example.png
  docs/source/dev_guide/_static/cdp_index_page.png
  docs/source/dev_guide/_static/cdp_page.png
  docs/source/dev_guide/_static/git-flow.svg
  docs/source/dev_guide/_static/pre-commit-flow.svg
  docs/source/dev_guide/index.rst
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/releasing-e3sm-diags.rst
  docs/source/dev_guide/using-cdp-output-viewer.rst
  docs/source/index.rst
Labels: documentation

#443 Address FIXME comments
  acme_diags/acme_diags_vars.py
  acme_diags/container/e3sm_diags_container.py
  acme_diags/derivations/acme.py
  acme_diags/driver/area_mean_time_series_driver.py
  acme_diags/driver/arm_diags_driver.py
  acme_diags/driver/diurnal_cycle_driver.py
  acme_diags/driver/meridional_mean_2d_driver.py
  acme_diags/driver/qbo_driver.py
  acme_diags/driver/streamflow_driver.py
  acme_diags/driver/utils/general.py
  acme_diags/parameter/enso_diags_parameter.py
  acme_diags/parameter/qbo_parameter.py
  acme_diags/parameter/streamflow_parameter.py
  acme_diags/parameter/time_series_parameter.py
  acme_diags/plot/cartopy/area_mean_time_series_plot.py
  acme_diags/plot/cartopy/arm_diags_plot.py
  acme_diags/plot/cartopy/diurnal_cycle_plot.py
  acme_diags/plot/cartopy/qbo_plot.py
  acme_diags/plot/cartopy/streamflow_plot.py
  acme_diags/viewer/arm_diags_viewer.py
  acme_diags/viewer/streamflow_viewer.py
  tests/acme_diags/derivations/test_acme.py
Labels: enhancement
