Repository E3SM-Project/e3sm_diags, pull requests merged in 2021-08, with the labels that each got.

#497 Enable ability to manually update docs on `gh-pages`
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  docs/source/conf.py
Labels: bug

#498 Update CI/CD workflows to only regenerate master docs
  .github/workflows/release_workflow.yml
Labels: bug

#500 Update `publish-docs` job in `release_workflow.yml`
  .github/workflows/release_workflow.yml
Labels: DevOps

#494 Add tbump to simplify package versioning
  Dockerfile
  conda/e3sm_diags_env.yml
  conda/e3sm_diags_env_dev.yml
  docs/source/_static/available-parameters/.!43922!parameter_example.png
  docs/source/_static/available-parameters/.!44994!parameter_example.png
  docs/source/_static/colormaps/.!43937!ceres_ebaf_toa_v4.0-NETCF-ANN-global.png
  docs/source/_static/colormaps/.!43938!GPCP_v2.2-PRECT-ANN-global.png
  docs/source/_static/colormaps/.!43939!ERA-Interim-U-850-ANN-global.png
  docs/source/_static/colormaps/.!45022!ceres_ebaf_toa_v4.0-NETCF-ANN-global.png
  docs/source/_static/colormaps/.!45023!GPCP_v2.2-PRECT-ANN-global.png
  docs/source/_static/colormaps/.!45025!ERA-Interim-U-850-ANN-global.png
  docs/source/_static/quick-guide-aims4/.!43935!performance_test.png
  docs/source/_static/quick-guide-aims4/.!45019!performance_test.png
  docs/source/_static/releasing-e3sm-diags/.!43923!.DS_Store
  docs/source/_static/releasing-e3sm-diags/.!43924!github_release.png
  docs/source/_static/releasing-e3sm-diags/.!44996!.DS_Store
  docs/source/_static/releasing-e3sm-diags/.!44998!github_release.png
  docs/source/_static/releasing-e3sm-diags/github_release.png
  docs/source/dev_guide/releasing-e3sm-diags.rst
  tbump.toml
Labels: DevOps, enhancement

#508 Update dev install docs
  docs/source/install.rst
Labels: documentation

#513 Fix quick guides
  README.md
  docs/source/quickguides/index.rst
  docs/source/quickguides/quick-guide-acme1.rst
  docs/source/quickguides/quick-guide-anvil.rst
  docs/source/quickguides/quick-guide-chrysalis.rst
  docs/source/quickguides/quick-guide-compy.rst
  docs/source/quickguides/quick-guide-cori-haswell.rst
  docs/source/quickguides/quick-guide-general.rst
  docs/source/quickguides/quick-guide-generic.rst
Labels: documentation

#516 Add xml support for get_static_var
  e3sm_diags/driver/utils/dataset.py
Labels: bug, new feature
