Repository E3SM-Project/e3sm_diags, pull requests merged in 2021-03, with the labels that each got.

#399 Update flake8 repo URL for pre-commit
  .pre-commit-config.yaml
  conda/e3sm_diags_env_dev.yml
Labels: bug

#397 v2.4.0 tutorial
  .gitignore
  examples/tutorials/tutorial_v2_4_0_all_sets_E3SM_machines.py
  tests/complete_run.py
Labels: testing

#407 Update .gitignore and remove unused files
  .DS_Store
  .Dockerfile.un~
  .gitignore
  .setup.py.un~
Labels: documentation, enhancement

#410 Add publish to Anaconda workflow
  .github/workflows/publish_to_anaconda.yml
  .github/workflows/workflow.yml
  docs/source/contributing.rst
Labels: DevOps, documentation

#414 Scale data to minimum number of months
  acme_diags/plot/cartopy/qbo_plot.py
Labels: enhancement

#417 Update remote names
  docs/source/contributing.rst
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/releasing-e3sm-diags.rst
  docs/source/install.rst
Labels: documentation

#420 Update release steps
  docs/source/dev_guide/releasing-e3sm-diags.rst
Labels: documentation

#422 Update release workflow to trigger building docs
  .github/workflows/publish_to_anaconda.yml
  .github/workflows/release_workflow.yml
Labels: DevOps

#424 Add acme_ne30_ocean_land_mask.nc to be tracked
  .gitignore
Labels: DevOps

#429 Remove setup-miniconda pinned python version
  .github/workflows/workflow.yml
Labels: DevOps

#425 Fail if any part fails
  acme_diags/acme_diags_driver.py
  acme_diags/parameter/core_parameter.py
  docs/source/available-parameters.rst
Labels: enhancement
