Repository E3SM-Project/e3sm_diags, pull requests merged in 2021-06, with the labels that each got.

#462 Patch to turn off image comparison
  .github/workflows/build_workflow.yml
  tests/system/test_diags.py
Labels: bug

#466 Stop tests if unit tests fail
  tests/test.sh
Labels: testing

#472 Update dependencies in env and recipe
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  .pre-commit-config.yaml
  acme_diags/derivations/acme.py
  conda/e3sm_diags_env.yml
  conda/e3sm_diags_env_dev.yml
  conda/meta.yaml
  docs/source/install.rst
Labels: DevOps

#474 Get tests passing for rc2
  conda/e3sm_diags_env.yml
  conda/e3sm_diags_env_dev.yml
  tests/download_data.py
  tests/system/test_diags.py
Labels: bug, testing

#468 Add CDMS_NO_MPI env variable
  acme_diags/__init__.py
  acme_diags/acme_diags_driver.py
  acme_diags/acme_diags_vars.py
  analysis_data_preprocess/create_OAFLUX_climo.py
  analysis_data_preprocess/create_PminusE_GPCP-OAFlux_timeseries.py
  analysis_data_preprocess/fix_units_TRMM-3B43v-7_3hr.py
Labels: DevOps

#463 v2.5.0rc2 update
  Dockerfile
  acme_diags/__init__.py
  conda/e3sm_diags_env.yml
  conda/meta.yaml
  setup.py
Labels: update version

#476 Improve testing
  .gitignore
  docs/source/dev_guide/testing.rst
  tests/all_sets_nightly_model_vs_model.py
  tests/all_sets_nightly_model_vs_obs.py
  tests/clean_tests_repo.sh
  tests/integration/all_sets.cfg
  tests/integration/all_sets.py
  tests/integration/all_sets_modified.cfg
  tests/integration/download_data.py
  tests/integration/test_all_sets.py
  tests/integration/test_dataset.py
  tests/integration/test_diags.py
  tests/integration/test_run.py
  tests/system/model_climo_vs_model_climo.py
  tests/system/model_climo_vs_obs_climo.py
  tests/system/model_ts_vs_obs_ts.py
  tests/system/model_vs_model.cfg
  tests/system/model_vs_obs.cfg
  tests/test.sh
Labels: documentation, testing
