Repository E3SM-Project/e3sm_diags, pull requests merged in 2021-02, with the labels that each got.

#388 Update expected images path and add diffs
  tests/complete_run_v2_3_0.py
  tests/system/test_diags.py
Labels: testing

#385 Integrate GitHub Actions CI/CD workflow
  .github/workflows/workflow.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  acme_diags/driver/default_diags/area_mean_time_series_model_vs_obs.cfg
  acme_diags/driver/default_diags/arm_diags_model_vs_model.cfg
  acme_diags/driver/default_diags/arm_diags_model_vs_obs.cfg
  acme_diags/driver/default_diags/cosp_histogram_model_vs_obs.cfg
  acme_diags/driver/default_diags/enso_NINO3.long.data
  acme_diags/driver/default_diags/enso_NINO34.long.data
  acme_diags/driver/default_diags/enso_NINO4.long.data
  acme_diags/driver/default_diags/lat_lon_model_vs_model.cfg
  acme_diags/driver/default_diags/lat_lon_model_vs_obs.cfg
  acme_diags/driver/default_diags/legacy_diags/lat_lon_ACME.json
  acme_diags/driver/default_diags/legacy_diags/lat_lon_AMWG.json
  acme_diags/driver/default_diags/legacy_diags/polar_ACME.json
  acme_diags/driver/default_diags/legacy_diags/polar_AMWG.json
  acme_diags/driver/default_diags/legacy_diags/zonal_mean_xy_ACME.json
  acme_diags/driver/default_diags/meridional_mean_2d_model_vs_model.cfg
  acme_diags/driver/default_diags/polar_model_vs_model.cfg
  acme_diags/driver/default_diags/polar_model_vs_obs.cfg
  acme_diags/driver/default_diags/zonal_mean_2d_model_vs_model.cfg
  acme_diags/driver/default_diags/zonal_mean_xy_model_vs_model.cfg
  acme_diags/driver/default_diags/zonal_mean_xy_model_vs_obs.cfg
  acme_diags/plot/colormaps/WhiteBlueGreenYellowRed.rgb
  acme_diags/viewer/index_template.html
  analysis_data_preprocess/README
  analysis_data_preprocess/create_COREv2_Flux_climo.sh
  analysis_data_preprocess/create_ERA-Interim_climo.sh
  analysis_data_preprocess/create_ERA5_U_climo.sh
  analysis_data_preprocess/create_ERA5_climo.sh
  analysis_data_preprocess/create_GPCP_1DD_climo.sh
  analysis_data_preprocess/create_HadISST_climo.sh
  analysis_data_preprocess/create_ISLSCPII_COMP_RUNOFF_climo.sh
  analysis_data_preprocess/create_MERRA2_climo.sh
  analysis_data_preprocess/create_PminusE_GPCP-OAFlux_climo.sh
  analysis_data_preprocess/create_ceres_ebaf_surface_climo.sh
  analysis_data_preprocess/create_ceres_ebaf_toa_climo.sh
  analysis_data_preprocess/obs_data.yml
  circle.yml
  conda/e3sm_diags_env_testing.yml
  conda/meta.yaml
  examples/ex7-obs-vs-obs/diags.cfg
  examples/tutorials/postprocessing_E3SM_data_for_e3sm_diags.sh
  examples/tutorials/postprocessing_E3SM_data_for_single_sites.sh
  pyproject.toml
  setup.cfg
  tests/system/all_sets.cfg
  tests/system/all_sets_modified.cfg
  travis_env.yml
Labels: enhancement, testing

#389 Docs for testing
  docs/doctrees/dev_guide/index.doctree
  docs/doctrees/dev_guide/testing.doctree
  docs/doctrees/environment.pickle
  docs/html/_sources/dev_guide/index.rst.txt
  docs/html/_sources/dev_guide/testing.rst.txt
  docs/html/contributing.html
  docs/html/dev_guide/adding-new-diags-sets.html
  docs/html/dev_guide/create-new-env.html
  docs/html/dev_guide/index.html
  docs/html/dev_guide/releasing-e3sm-diags.html
  docs/html/dev_guide/testing.html
  docs/html/index.html
  docs/html/objects.inv
  docs/html/searchindex.js
  source/dev_guide/index.rst
  source/dev_guide/testing.rst
Labels: documentation

#391 Improve complete_run workflow
  .gitignore
  tests/complete_run.py
Labels: testing
