Repository E3SM-Project/e3sm_diags, pull requests merged in 2023-06, with the labels that each got.

#694 Fix `numpy.int` --> `int`
  analysis_data_preprocess/create_GPCP_climo.py
  analysis_data_preprocess/create_OAFLUX_climo.py
  e3sm_diags/driver/utils/climo.py
  e3sm_diags/driver/utils/diurnal_cycle.py
Labels: bug

#693 Change workflow to mamba
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/docs.yml
  docs/source/install.rst
Labels: documentation, DevOps

#696 Simplify the conda env yml files
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/docs.yml
  conda-env/prod.yml
  tbump.toml
Labels: DevOps

#698 Fix release workflow not copying docs for latest tags
  .github/workflows/release_workflow.yml
Labels: bug, DevOps

#697 Bump to 2.9.0rc1
  e3sm_diags/__init__.py
  setup.py
  tbump.toml
Labels: update version

#699 Fix dir ref in release workflow
  .github/workflows/release_workflow.yml
Labels: DevOps
