Repository E3SM-Project/e3sm_diags, pull requests merged in 2025-03, with the labels that each got.

#940 Standardize regridding to `conservative_normed`
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/complete_run/regression_nc.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/complete_run/regression_png.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/complete_run/run_script.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/fix-polar-plots/debug_diffs.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/fix-polar-plots/debug_diffs_min.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/fix-polar-plots/debug_polar_diffs.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/fix-polar-plots/v2_run.cfg
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/fix-polar-plots/v2_run_script.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/1_debug_sst_rmse_2_12_1_datasets.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/2_debug_sst_rmse_3_0_0_datasets.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/3_debug_sst_post_regrid_datasets.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/4_debug_sst_rmse_weights.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/4_debug_sst_rmse_weights.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/5_debug_sst_fixed_weights.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/Regridding_diff_with_original_bounds.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/Regridding_methods_comparison.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/final_rmse_debug_script.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/run.cfg
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/rmse-diffs/run.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/specific-vars/regression_nc.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/specific-vars/regression_nc_diffs.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/specific-vars/regression_png.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/specific-vars/v2_run.cfg
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/specific-vars/v2_run_script.py
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/trefht-land/regression_nc.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/trefht-land/regression_nc_diffs.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/trefht-land/regression_png.ipynb
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/trefht-land/v2_run.cfg
  auxiliary_tools/cdat_regression_testing/940-xesmf-diffs/trefht-land/v2_run_script.py
  e3sm_diags/driver/utils/regrid.py
  e3sm_diags/parameter/core_parameter.py
  tests/e3sm_diags/driver/utils/test_regrid.py
Labels: bug, enhancement, cdat-migration-fy24

#947 Bump to 3.0.0rc4
  e3sm_diags/__init__.py
  tbump.toml
Labels: update version

#958 Fix xESMF `UserWarning: Input array is not C_CONTIGUOUS...`
  auxiliary_tools/cdat_regression_testing/932-xesmf-warning/mvce.py
  auxiliary_tools/cdat_regression_testing/932-xesmf-warning/run.cfg
  auxiliary_tools/cdat_regression_testing/932-xesmf-warning/run_script.py
  e3sm_diags/driver/utils/regrid.py
  tests/e3sm_diags/driver/utils/test_regrid.py
Labels: cdat-migration-fy24

#959 Skip regriding for two datasets on same lat-lon grids
  e3sm_diags/driver/utils/regrid.py
  tests/e3sm_diags/driver/utils/test_regrid.py
Labels: enhancement

#925 Update documentation for v3.0.0 release
  Makefile
  README.md
  conda-env/ci.yml
  conda-env/dev.yml
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/quickguides/generate_quick_guides.py
  docs/source/quickguides/index.rst
  docs/source/quickguides/old/index.rst
  docs/source/quickguides/old/quick-guide-aims4.rst
  docs/source/quickguides/old/quick-guide-compy.rst
  docs/source/quickguides/old/quick-guide-cooley.rst
  docs/source/quickguides/old/quick-guide-cori-haswell.rst
  docs/source/quickguides/old/quick-guide-cori.rst
  docs/source/quickguides/old/quick-guide-docker.rst
  docs/source/quickguides/old/quick-guide-edison-shifter.rst
  docs/source/quickguides/old/quick-guide-edison.rst
  docs/source/quickguides/old/quick-guide-multiprocessing-cori-haswell.rst
  docs/source/quickguides/old/quick-guide-rhea.rst
  docs/source/quickguides/quick-guide-acme1.rst
  docs/source/quickguides/quick-guide-anvil.rst
  docs/source/quickguides/quick-guide-chrysalis.rst
  docs/source/quickguides/quick-guide-compy.rst
  docs/source/quickguides/quick-guide-general.rst
  docs/source/quickguides/quick-guide-generic.rst
  docs/source/quickguides/quick-guide-perlmutter.rst
  pyproject.toml
Labels: documentation

#956 Bump to v3.0.0
  e3sm_diags/__init__.py
  tbump.toml
Labels: update version, cdat-migration-fy24

#963 Add support for saving regridded datasets to netCDF files
  e3sm_diags/driver/annual_cycle_zonal_mean_driver.py
  e3sm_diags/driver/cosp_histogram_driver.py
  e3sm_diags/driver/lat_lon_driver.py
  e3sm_diags/driver/meridional_mean_2d_driver.py
  e3sm_diags/driver/polar_driver.py
  e3sm_diags/driver/utils/io.py
  e3sm_diags/driver/zonal_mean_2d_driver.py
  e3sm_diags/parser/meridional_mean_2d_parser.py
Labels: Easy
