Repository E3SM-Project/e3sm_diags, pull requests merged in 2025-01, with the labels that each got.

#880 EAMxx variables
  .github/workflows/build_workflow.yml
  auxiliary_tools/cdat_regression_testing/892-bottleneck/debug_ref_u.py
  auxiliary_tools/cdat_regression_testing/892-bottleneck/run_script.cfg
  auxiliary_tools/cdat_regression_testing/892-bottleneck/run_script.py
  auxiliary_tools/cdat_regression_testing/892-bottleneck/xr_mvce_e3sm_data.py
  auxiliary_tools/cdat_regression_testing/892-bottleneck/xr_mvce_gh.py
  e3sm_diags/derivations/derivations.py
  e3sm_diags/derivations/formulas.py
  e3sm_diags/driver/__init__.py
  e3sm_diags/driver/aerosol_budget_driver.py
  e3sm_diags/driver/utils/climo_xr.py
  e3sm_diags/driver/utils/dataset_xr.py
  e3sm_diags/driver/utils/regrid.py
  e3sm_diags/metrics/metrics.py
  examples/e3sm_diags_for_eamxx/README.md
  examples/e3sm_diags_for_eamxx/nco.sh
  examples/e3sm_diags_for_eamxx/run_e3sm_diags_1996.py
  examples/e3sm_diags_for_eamxx/run_e3sm_diags_climo.py
  tests/e3sm_diags/driver/utils/test_dataset_xr.py
Labels: enhancement

#919 Drop Python 3.9 support
  .github/workflows/build_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  pyproject.toml
  setup.py
Labels: DevOps

#927 Add viewer `index.html` to top level of results directory
  auxiliary_tools/cdat_regression_testing/562-index-html/562_index_html.cfg
  auxiliary_tools/cdat_regression_testing/562-index-html/run_script.py
  e3sm_diags/e3sm_diags_driver.py
  e3sm_diags/viewer/core_viewer.py
  e3sm_diags/viewer/main.py
Labels: documentation
