Repository E3SM-Project/e3sm_diags, pull requests merged in 2025-05, with the labels that each got.

#980 Update `setup-miniconda` from v2 to v3
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
Labels: DevOps

#974 Creates a mask for 2d datasets before regridding
  e3sm_diags/driver/utils/regrid.py
  tests/e3sm_diags/driver/utils/test_regrid.py
Labels: enhancement

#972 Add `pad_year` function for xarray time slicing with years <1000
  .github/workflows/build_workflow.yml
  auxiliary_tools/debug/971-iso-8601/debug.py
  e3sm_diags/driver/tropical_subseasonal_driver.py
  e3sm_diags/driver/utils/dataset_xr.py
  e3sm_diags/driver/utils/general.py
  e3sm_diags/parameter/core_parameter.py
  tests/e3sm_diags/driver/utils/test_dataset_xr.py
  tests/e3sm_diags/driver/utils/test_general.py
  tests/e3sm_diags/test_parameters.py
Labels: bug
